language: 'cpp'
sudo: 'required'

cache:
  directories:
    - '${HOME}/downloads'

env:
  global:
    - PREBUILT_BOOST_DOWNLOAD_URL: 'https://dl.bintray.com/mabrarov/generic/boost'
    - DEPENDENCIES_HOME: '${HOME}/dependencies'
    - DOWNLOADS_HOME: '${HOME}/downloads'
    - BUILD_HOME: '${TRAVIS_BUILD_DIR}/build'
    - CURL_CONNECT_TIMEOUT: '300'
    - CURL_MAX_TIME: '1800'
    - CURL_RETRY: '10'
    - CURL_RETRY_DELAY: '10'
    - STRAND_TEST_USE_STRAND_WRAP: '1'
    - STRAND_TEST_THREAD_NUM: '100'
    - STRAND_TEST_HANDLER_DURATION: '100'
    - STRAND_TEST_INIT_HANDLER_NUM: '400'
    - STRAND_TEST_CONCURRENT_HANDLER_NUM: '400'
    - STRAND_TEST_STRAND_HANDLER_NUM: '200'

matrix:
  include:
    # GCC 10, Boost 1.74.0
    - os: 'linux'
      dist: 'bionic'
      env:
        - C_COMPILER: 'gcc-10'
        - CXX_COMPILER: 'g++-10'
        - CMAKE_VERSION: '3.19.1'
        - BOOST_VERSION: '1.74.0'
        - BUILD_TYPE: 'RELEASE'
      compiler: 'gcc'
      addons: &apt-gcc10-boost174
        apt:
          packages:
            - 'cmake'
            - 'cmake-data'
            - 'gcc-10'
            - 'g++-10'
            - 'curl'
            - 'ca-certificates'
            - 'libboost1.74-dev'
          sources:
            - 'ubuntu-toolchain-r-test'
            - sourceline: 'ppa:mhier/libboost-latest'
    - os: 'linux'
      dist: 'bionic'
      env:
        - C_COMPILER: 'gcc-10'
        - CXX_COMPILER: 'g++-10'
        - CMAKE_VERSION: '3.19.1'
        - BOOST_VERSION: '1.74.0'
        - BUILD_TYPE: 'DEBUG'
      compiler: 'gcc'
      addons: *apt-gcc10-boost174
    # Clang 10.0, Boost 1.74.0
    - os: 'linux'
      dist: 'bionic'
      env:
        - C_COMPILER: 'clang-10'
        - CXX_COMPILER: 'clang++-10'
        - CMAKE_VERSION: '3.19.1'
        - BOOST_VERSION: '1.74.0'
        - BUILD_TYPE: 'RELEASE'
      compiler: 'clang'
      addons: &apt-clang10-boost174
        apt:
          packages:
            - 'cmake'
            - 'cmake-data'
            - 'clang-10'
            - 'libboost1.74-dev'
          sources:
            - 'ubuntu-toolchain-r-test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'ppa:mhier/libboost-latest'
    - os: 'linux'
      dist: 'bionic'
      env:
        - C_COMPILER: 'clang-10'
        - CXX_COMPILER: 'clang++-10'
        - CMAKE_VERSION: '3.19.1'
        - BOOST_VERSION: '1.74.0'
        - BUILD_TYPE: 'DEBUG'
      compiler: 'clang'
      addons: *apt-clang10-boost174
    # MacOS, Clang Apple LLVM version 11.3, Boost 1.74.0
    - os: 'osx'
      osx_image: 'xcode11.3'
      env:
        - C_COMPILER: 'clang'
        - CXX_COMPILER: 'clang++'
        - BOOST_VERSION: '1.74.0'
        - BUILD_TYPE: 'RELEASE'
      compiler: 'clang'
      addons: &homebrew-boost174
        homebrew:
          packages:
            - 'gnu-sed'
            - 'cmake'
            - 'boost@1.74'
          update: true
    - os: 'osx'
      osx_image: 'xcode11.3'
      env:
        - C_COMPILER: 'clang'
        - CXX_COMPILER: 'clang++'
        - BOOST_VERSION: '1.74.0'
        - BUILD_TYPE: 'DEBUG'
      compiler: 'clang'
      addons: *homebrew-boost174

install: 'source ./scripts/travis/install.sh'
script: './scripts/travis/build.sh'
